### ISSUE TITLE
Not working on Arduino 1.0.5

### ISSUE THREAD

**Issue by ayushgaud** [jrowberg/i2cdevlib#38]
not able to compile the program showing this error \Arduino\hardware\arduino\cores\arduino/Arduino.h:105:26: error: macro "millis" passed 1 arguments, but takes just 0

**Comment by likhithasrinivas** [comment]
Hi,

Despite of adding all libraries I am finding the below error. Can anyone please help me out.
Thanks

Arduino: 1.6.5 (Windows 8.1), Board: "Intel® Edison"

MPU9150_raw.ino:38:20: fatal error: I2Cdev.h: No such file or directory
compilation terminated.
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
